/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontend;

/**
 *
 * @author Nahum
 */
public class VClientes extends javax.swing.JFrame {

    /**
     * Creates new form VClientes
     */
    public VClientes() 
    {
        initComponents();
        Body_Inicio.setVisible(true);
        Body_Ganador.setVisible(false);
        Body_Estadísticas.setVisible(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JPanel();
        LB_Titulo = new javax.swing.JLabel();
        Btn_Salir = new javax.swing.JButton();
        Btn_Verificar = new javax.swing.JButton();
        Btn_Estadisticas = new javax.swing.JButton();
        Btn_Inicio = new javax.swing.JButton();
        Body_Inicio = new javax.swing.JPanel();
        Panel_Inicio_Loteria = new javax.swing.JPanel();
        LabelTitulo = new javax.swing.JLabel();
        Label_Fecha_Loteria = new javax.swing.JLabel();
        LB_Titulo_Loteria = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        LB_PP_Monto_Loteria = new javax.swing.JLabel();
        LB_PP_Numero_Loteria = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        LB_PP_Serie_Loteria = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        LB_SP_Monto_Loteria = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        LB_SP_Numero_Loteria = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        LB_SP_Serie_Loteria = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        LB_TP_Monto_Loteria = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        LB_TP_Numero_Loteria = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        LB_TP_Serie_Loteria = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        Panel_Inicio_Chances = new javax.swing.JPanel();
        LabelTitulo1 = new javax.swing.JLabel();
        Label_Fecha_Chances = new javax.swing.JLabel();
        LB_Titulo_Chances = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        LB_PP_Monto_Chances = new javax.swing.JLabel();
        LB_PP_Numero_Chances = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        LB_PP_Serie_Chances = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        LB_SP_Monto_Chances = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        LB_SP_Numero_Chances = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        LB_SP_Serie_Chances = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        LB_TP_Monto_Chances = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        LB_TP_Numero_Chances = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        LB_TP_Serie_Chances = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        Lb_FondoI = new javax.swing.JLabel();
        Body_Estadísticas = new javax.swing.JPanel();
        Panel_Contenedor_Estadisticas = new javax.swing.JTabbedPane();
        Panel_Estadisticas = new javax.swing.JPanel();
        jLabel64 = new javax.swing.JLabel();
        CB_Filtro_estadistica = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabla_Estadisticas = new javax.swing.JTable();
        jLabel65 = new javax.swing.JLabel();
        CB_Consulta_estadistica = new javax.swing.JComboBox<>();
        btn_buscar_estadisticas = new javax.swing.JButton();
        Panel_EXportar = new javax.swing.JPanel();
        btn_exportar = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        Tabla_Exportar = new javax.swing.JTable();
        jLabel66 = new javax.swing.JLabel();
        CB_Tipo_Exportar = new javax.swing.JComboBox<>();
        jLabel67 = new javax.swing.JLabel();
        Campo_Numero_Exportar = new javax.swing.JTextField();
        btn_buscar_exportar = new javax.swing.JButton();
        Lb_FondoG1 = new javax.swing.JLabel();
        Body_Ganador = new javax.swing.JPanel();
        Panel_Ganador = new javax.swing.JPanel();
        LabelTitulo2 = new javax.swing.JLabel();
        Panel_Input_Ganador = new javax.swing.JPanel();
        LB_Etiqueta = new javax.swing.JLabel();
        LB_Etiqueta2 = new javax.swing.JLabel();
        LB_Etiqueta1 = new javax.swing.JLabel();
        Campo_Numero_Ganador = new javax.swing.JTextField();
        Campo_Serie_Ganador = new javax.swing.JTextField();
        CB_Tipo_Sorteo_Ganador = new javax.swing.JComboBox<>();
        btn_Buscar = new javax.swing.JButton();
        LB_Titulo_Resultado = new javax.swing.JLabel();
        LB_Contenido_Resultado = new javax.swing.JLabel();
        LB_Etiqueta3 = new javax.swing.JLabel();
        Campo_Numero_Sorteo_Ganador = new javax.swing.JTextField();
        Lb_FondoG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Header.setBackground(new java.awt.Color(39, 33, 60));

        LB_Titulo.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        LB_Titulo.setForeground(new java.awt.Color(255, 255, 255));
        LB_Titulo.setText("BigPrizes.sn");

        Btn_Salir.setBackground(new java.awt.Color(39, 33, 60));
        Btn_Salir.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Btn_Salir.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Salir.setText("| Salir");
        Btn_Salir.setBorder(null);
        Btn_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SalirActionPerformed(evt);
            }
        });

        Btn_Verificar.setBackground(new java.awt.Color(39, 33, 60));
        Btn_Verificar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Btn_Verificar.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Verificar.setText("|  Verificar ganador");
        Btn_Verificar.setBorder(null);
        Btn_Verificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_VerificarActionPerformed(evt);
            }
        });

        Btn_Estadisticas.setBackground(new java.awt.Color(39, 33, 60));
        Btn_Estadisticas.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Btn_Estadisticas.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Estadisticas.setText(" |  Estadísticas");
        Btn_Estadisticas.setBorder(null);
        Btn_Estadisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_EstadisticasActionPerformed(evt);
            }
        });

        Btn_Inicio.setBackground(new java.awt.Color(39, 33, 60));
        Btn_Inicio.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Btn_Inicio.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Inicio.setText("Inicio");
        Btn_Inicio.setBorder(null);
        Btn_Inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_InicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(Btn_Inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn_Verificar, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Btn_Estadisticas)
                .addGap(18, 18, 18)
                .addComponent(Btn_Salir)
                .addGap(380, 380, 380)
                .addComponent(LB_Titulo)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LB_Titulo)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Btn_Verificar)
                        .addComponent(Btn_Inicio))
                    .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Btn_Estadisticas)
                        .addComponent(Btn_Salir))))
        );

        getContentPane().add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, -1));

        Body_Inicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel_Inicio_Loteria.setBackground(new java.awt.Color(204, 204, 255));

        LabelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        LabelTitulo.setText("Lotería nacional");

        Label_Fecha_Loteria.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Label_Fecha_Loteria.setText("04/11/2019");

        LB_Titulo_Loteria.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LB_Titulo_Loteria.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LB_Titulo_Loteria.setText("Sorteo 1200000");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Primer premio");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Segundo premio");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Primer premio");

        LB_PP_Monto_Loteria.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LB_PP_Monto_Loteria.setText(" ₡250 000 000");

        LB_PP_Numero_Loteria.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LB_PP_Numero_Loteria.setText("79");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel14.setText("Número");

        LB_PP_Serie_Loteria.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LB_PP_Serie_Loteria.setText("555");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel15.setText("serie");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel16.setText("por entero");

        LB_SP_Monto_Loteria.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LB_SP_Monto_Loteria.setText(" ₡250 000 000");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel17.setText("por entero");

        LB_SP_Numero_Loteria.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LB_SP_Numero_Loteria.setText("79");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel18.setText("Número");

        LB_SP_Serie_Loteria.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LB_SP_Serie_Loteria.setText("555");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel19.setText("serie");

        LB_TP_Monto_Loteria.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LB_TP_Monto_Loteria.setText(" ₡250 000 000");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel20.setText("por entero");

        LB_TP_Numero_Loteria.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LB_TP_Numero_Loteria.setText("79");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel21.setText("Número");

        LB_TP_Serie_Loteria.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LB_TP_Serie_Loteria.setText("555");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel22.setText("serie");

        javax.swing.GroupLayout Panel_Inicio_LoteriaLayout = new javax.swing.GroupLayout(Panel_Inicio_Loteria);
        Panel_Inicio_Loteria.setLayout(Panel_Inicio_LoteriaLayout);
        Panel_Inicio_LoteriaLayout.setHorizontalGroup(
            Panel_Inicio_LoteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Inicio_LoteriaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_Inicio_LoteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_Inicio_LoteriaLayout.createSequentialGroup()
                        .addComponent(LabelTitulo)
                        .addGap(120, 120, 120)
                        .addComponent(Label_Fecha_Loteria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Panel_Inicio_LoteriaLayout.createSequentialGroup()
                        .addGroup(Panel_Inicio_LoteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LB_Titulo_Loteria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(424, 424, 424)))
                .addContainerGap())
            .addGroup(Panel_Inicio_LoteriaLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(Panel_Inicio_LoteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Panel_Inicio_LoteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(Panel_Inicio_LoteriaLayout.createSequentialGroup()
                            .addGroup(Panel_Inicio_LoteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(LB_SP_Monto_Loteria)
                                .addGroup(Panel_Inicio_LoteriaLayout.createSequentialGroup()
                                    .addGap(50, 50, 50)
                                    .addComponent(jLabel17)))
                            .addGap(75, 75, 75)
                            .addGroup(Panel_Inicio_LoteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel18)
                                .addGroup(Panel_Inicio_LoteriaLayout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(LB_SP_Numero_Loteria)))
                            .addGap(19, 19, 19)
                            .addGroup(Panel_Inicio_LoteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(LB_SP_Serie_Loteria)
                                .addComponent(jLabel19)))
                        .addGroup(Panel_Inicio_LoteriaLayout.createSequentialGroup()
                            .addGroup(Panel_Inicio_LoteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(LB_TP_Monto_Loteria)
                                .addGroup(Panel_Inicio_LoteriaLayout.createSequentialGroup()
                                    .addGap(50, 50, 50)
                                    .addComponent(jLabel20)))
                            .addGap(75, 75, 75)
                            .addGroup(Panel_Inicio_LoteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel21)
                                .addGroup(Panel_Inicio_LoteriaLayout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(LB_TP_Numero_Loteria)))
                            .addGap(19, 19, 19)
                            .addGroup(Panel_Inicio_LoteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(LB_TP_Serie_Loteria)
                                .addComponent(jLabel22))
                            .addGap(1, 1, 1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Panel_Inicio_LoteriaLayout.createSequentialGroup()
                        .addGroup(Panel_Inicio_LoteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LB_PP_Monto_Loteria)
                            .addGroup(Panel_Inicio_LoteriaLayout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jLabel16)))
                        .addGap(75, 75, 75)
                        .addGroup(Panel_Inicio_LoteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addGroup(Panel_Inicio_LoteriaLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(LB_PP_Numero_Loteria)))
                        .addGap(19, 19, 19)
                        .addGroup(Panel_Inicio_LoteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LB_PP_Serie_Loteria)
                            .addComponent(jLabel15))
                        .addGap(60, 60, 60))))
        );
        Panel_Inicio_LoteriaLayout.setVerticalGroup(
            Panel_Inicio_LoteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Inicio_LoteriaLayout.createSequentialGroup()
                .addGroup(Panel_Inicio_LoteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelTitulo)
                    .addComponent(Label_Fecha_Loteria, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(LB_Titulo_Loteria)
                .addGap(30, 30, 30)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(Panel_Inicio_LoteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LB_PP_Monto_Loteria, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LB_PP_Numero_Loteria, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LB_PP_Serie_Loteria, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Panel_Inicio_LoteriaLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(Panel_Inicio_LoteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(29, 29, 29)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(Panel_Inicio_LoteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LB_SP_Monto_Loteria, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LB_SP_Numero_Loteria, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LB_SP_Serie_Loteria, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Panel_Inicio_LoteriaLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(Panel_Inicio_LoteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(44, 44, 44)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Panel_Inicio_LoteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LB_TP_Monto_Loteria, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LB_TP_Numero_Loteria, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LB_TP_Serie_Loteria, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Panel_Inicio_LoteriaLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(Panel_Inicio_LoteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(70, 70, 70))
        );

        Body_Inicio.add(Panel_Inicio_Loteria, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 420, 490));

        Panel_Inicio_Chances.setBackground(new java.awt.Color(204, 204, 255));

        LabelTitulo1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        LabelTitulo1.setText("Chances");

        Label_Fecha_Chances.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Label_Fecha_Chances.setText("04/11/2019");

        LB_Titulo_Chances.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LB_Titulo_Chances.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LB_Titulo_Chances.setText("Sorteo 1200000");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Primer premio");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("Segundo premio");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setText("Tercer premio");

        LB_PP_Monto_Chances.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LB_PP_Monto_Chances.setText(" ₡250 000 000");

        LB_PP_Numero_Chances.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LB_PP_Numero_Chances.setText("79");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel23.setText("Número");

        LB_PP_Serie_Chances.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LB_PP_Serie_Chances.setText("555");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel24.setText("serie");

        jLabel25.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel25.setText("por entero");

        LB_SP_Monto_Chances.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LB_SP_Monto_Chances.setText(" ₡250 000 000");

        jLabel26.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel26.setText("por entero");

        LB_SP_Numero_Chances.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LB_SP_Numero_Chances.setText("79");

        jLabel27.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel27.setText("Número");

        LB_SP_Serie_Chances.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LB_SP_Serie_Chances.setText("555");

        jLabel28.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel28.setText("serie");

        LB_TP_Monto_Chances.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LB_TP_Monto_Chances.setText(" ₡250 000 000");

        jLabel29.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel29.setText("por entero");

        LB_TP_Numero_Chances.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LB_TP_Numero_Chances.setText("79");

        jLabel30.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel30.setText("Número");

        LB_TP_Serie_Chances.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LB_TP_Serie_Chances.setText("555");

        jLabel31.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel31.setText("serie");

        javax.swing.GroupLayout Panel_Inicio_ChancesLayout = new javax.swing.GroupLayout(Panel_Inicio_Chances);
        Panel_Inicio_Chances.setLayout(Panel_Inicio_ChancesLayout);
        Panel_Inicio_ChancesLayout.setHorizontalGroup(
            Panel_Inicio_ChancesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Inicio_ChancesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_Inicio_ChancesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LB_Titulo_Chances, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(Panel_Inicio_ChancesLayout.createSequentialGroup()
                        .addGroup(Panel_Inicio_ChancesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(Panel_Inicio_ChancesLayout.createSequentialGroup()
                        .addComponent(LabelTitulo1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Label_Fecha_Chances)))
                .addContainerGap())
            .addGroup(Panel_Inicio_ChancesLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(Panel_Inicio_ChancesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Panel_Inicio_ChancesLayout.createSequentialGroup()
                        .addGroup(Panel_Inicio_ChancesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LB_PP_Monto_Chances)
                            .addGroup(Panel_Inicio_ChancesLayout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jLabel25)))
                        .addGap(75, 75, 75)
                        .addGroup(Panel_Inicio_ChancesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addGroup(Panel_Inicio_ChancesLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(LB_PP_Numero_Chances)))
                        .addGap(19, 19, 19)
                        .addGroup(Panel_Inicio_ChancesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LB_PP_Serie_Chances)
                            .addComponent(jLabel24)))
                    .addGroup(Panel_Inicio_ChancesLayout.createSequentialGroup()
                        .addGroup(Panel_Inicio_ChancesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(Panel_Inicio_ChancesLayout.createSequentialGroup()
                                .addGroup(Panel_Inicio_ChancesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LB_SP_Monto_Chances)
                                    .addGroup(Panel_Inicio_ChancesLayout.createSequentialGroup()
                                        .addGap(50, 50, 50)
                                        .addComponent(jLabel26)))
                                .addGap(75, 75, 75)
                                .addGroup(Panel_Inicio_ChancesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel27)
                                    .addGroup(Panel_Inicio_ChancesLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(LB_SP_Numero_Chances)))
                                .addGap(19, 19, 19)
                                .addGroup(Panel_Inicio_ChancesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LB_SP_Serie_Chances)
                                    .addComponent(jLabel28)))
                            .addGroup(Panel_Inicio_ChancesLayout.createSequentialGroup()
                                .addGroup(Panel_Inicio_ChancesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LB_TP_Monto_Chances)
                                    .addGroup(Panel_Inicio_ChancesLayout.createSequentialGroup()
                                        .addGap(50, 50, 50)
                                        .addComponent(jLabel29)))
                                .addGap(75, 75, 75)
                                .addGroup(Panel_Inicio_ChancesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel30)
                                    .addGroup(Panel_Inicio_ChancesLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(LB_TP_Numero_Chances)))
                                .addGap(19, 19, 19)
                                .addGroup(Panel_Inicio_ChancesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LB_TP_Serie_Chances)
                                    .addComponent(jLabel31))
                                .addGap(1, 1, 1)))
                        .addGap(1, 1, 1)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        Panel_Inicio_ChancesLayout.setVerticalGroup(
            Panel_Inicio_ChancesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Inicio_ChancesLayout.createSequentialGroup()
                .addGroup(Panel_Inicio_ChancesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelTitulo1)
                    .addComponent(Label_Fecha_Chances, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(LB_Titulo_Chances)
                .addGap(30, 30, 30)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(Panel_Inicio_ChancesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LB_PP_Monto_Chances, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LB_PP_Numero_Chances, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LB_PP_Serie_Chances, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Panel_Inicio_ChancesLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(Panel_Inicio_ChancesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(29, 29, 29)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addGroup(Panel_Inicio_ChancesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LB_SP_Monto_Chances, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LB_SP_Numero_Chances, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LB_SP_Serie_Chances, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Panel_Inicio_ChancesLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(Panel_Inicio_ChancesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(44, 44, 44)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Panel_Inicio_ChancesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LB_TP_Monto_Chances, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LB_TP_Numero_Chances, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LB_TP_Serie_Chances, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Panel_Inicio_ChancesLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(Panel_Inicio_ChancesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 31, Short.MAX_VALUE))
        );

        Body_Inicio.add(Panel_Inicio_Chances, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 90, -1, -1));

        Lb_FondoI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/lottery.png"))); // NOI18N
        Body_Inicio.add(Lb_FondoI, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 640));

        getContentPane().add(Body_Inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 62, -1, 640));

        Body_Estadísticas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel_Contenedor_Estadisticas.setBackground(new java.awt.Color(255, 255, 255));
        Panel_Contenedor_Estadisticas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        Panel_Estadisticas.setBackground(new java.awt.Color(255, 255, 255));
        Panel_Estadisticas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel64.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel64.setText("Filtrar por ");
        Panel_Estadisticas.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, -1, -1));

        CB_Filtro_estadistica.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CB_Filtro_estadistica.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lotería", "Chances" }));
        Panel_Estadisticas.add(CB_Filtro_estadistica, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, 140, 30));

        Tabla_Estadisticas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Tabla_Estadisticas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Tabla_Estadisticas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(Tabla_Estadisticas);

        Panel_Estadisticas.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 760, 270));

        jLabel65.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel65.setText("Consulta");
        Panel_Estadisticas.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, -1, -1));

        CB_Consulta_estadistica.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CB_Consulta_estadistica.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Top 5 más ganadores", "Probabilidad de números", "Top 5 más premiados" }));
        Panel_Estadisticas.add(CB_Consulta_estadistica, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 170, 30));

        btn_buscar_estadisticas.setBackground(new java.awt.Color(255, 153, 0));
        btn_buscar_estadisticas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_buscar_estadisticas.setForeground(new java.awt.Color(255, 255, 255));
        btn_buscar_estadisticas.setText("Buscar");
        btn_buscar_estadisticas.setBorder(null);
        btn_buscar_estadisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscar_estadisticasActionPerformed(evt);
            }
        });
        Panel_Estadisticas.add(btn_buscar_estadisticas, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 380, 150, 30));

        Panel_Contenedor_Estadisticas.addTab("Estadísticas", Panel_Estadisticas);

        Panel_EXportar.setBackground(new java.awt.Color(255, 255, 255));
        Panel_EXportar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_exportar.setBackground(new java.awt.Color(0, 0, 255));
        btn_exportar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_exportar.setForeground(new java.awt.Color(255, 255, 255));
        btn_exportar.setText("Exportar a PDF");
        btn_exportar.setBorder(null);
        Panel_EXportar.add(btn_exportar, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 380, 120, 30));

        Tabla_Exportar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Tabla_Exportar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Tabla_Exportar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane5.setViewportView(Tabla_Exportar);

        Panel_EXportar.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 760, 270));

        jLabel66.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel66.setText("Tipo");
        Panel_EXportar.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, -1, -1));

        CB_Tipo_Exportar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CB_Tipo_Exportar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Plan de premios", "Sorteos" }));
        Panel_EXportar.add(CB_Tipo_Exportar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 140, 30));

        jLabel67.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel67.setText("Filtrar por número");
        Panel_EXportar.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, -1, -1));
        Panel_EXportar.add(Campo_Numero_Exportar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, 150, 30));

        btn_buscar_exportar.setBackground(new java.awt.Color(255, 153, 0));
        btn_buscar_exportar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_buscar_exportar.setForeground(new java.awt.Color(255, 255, 255));
        btn_buscar_exportar.setText("Buscar");
        btn_buscar_exportar.setBorder(null);
        btn_buscar_exportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscar_exportarActionPerformed(evt);
            }
        });
        Panel_EXportar.add(btn_buscar_exportar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 380, 130, 30));

        Panel_Contenedor_Estadisticas.addTab("Exportar", Panel_EXportar);

        Body_Estadísticas.add(Panel_Contenedor_Estadisticas, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 1080, 500));

        Lb_FondoG1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/lottery.png"))); // NOI18N
        Body_Estadísticas.add(Lb_FondoG1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 640));

        getContentPane().add(Body_Estadísticas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 62, -1, 640));

        Body_Ganador.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel_Ganador.setBackground(new java.awt.Color(215, 216, 252));

        LabelTitulo2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        LabelTitulo2.setText("¿Desea saber si ganó algún permio?");

        Panel_Input_Ganador.setBackground(new java.awt.Color(204, 204, 255));
        Panel_Input_Ganador.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del sorteo"));

        LB_Etiqueta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LB_Etiqueta.setText("Tipo de sorteo");

        LB_Etiqueta2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LB_Etiqueta2.setText("Número");

        LB_Etiqueta1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LB_Etiqueta1.setText("Serie");

        CB_Tipo_Sorteo_Ganador.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lotería", "Chances" }));

        btn_Buscar.setBackground(new java.awt.Color(255, 153, 0));
        btn_Buscar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Buscar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Buscar.setText("Buscar");
        btn_Buscar.setBorder(null);
        btn_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BuscarActionPerformed(evt);
            }
        });

        LB_Titulo_Resultado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LB_Titulo_Resultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LB_Titulo_Resultado.setToolTipText("");

        LB_Contenido_Resultado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        LB_Etiqueta3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LB_Etiqueta3.setText("Numero de sorteo");

        javax.swing.GroupLayout Panel_Input_GanadorLayout = new javax.swing.GroupLayout(Panel_Input_Ganador);
        Panel_Input_Ganador.setLayout(Panel_Input_GanadorLayout);
        Panel_Input_GanadorLayout.setHorizontalGroup(
            Panel_Input_GanadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Input_GanadorLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(Panel_Input_GanadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Campo_Serie_Ganador)
                    .addComponent(Campo_Numero_Ganador)
                    .addComponent(LB_Etiqueta)
                    .addComponent(LB_Etiqueta2)
                    .addComponent(LB_Etiqueta1)
                    .addComponent(CB_Tipo_Sorteo_Ganador, 0, 219, Short.MAX_VALUE)
                    .addComponent(LB_Etiqueta3)
                    .addComponent(Campo_Numero_Sorteo_Ganador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 161, Short.MAX_VALUE)
                .addGroup(Panel_Input_GanadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LB_Titulo_Resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LB_Contenido_Resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78))
            .addGroup(Panel_Input_GanadorLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(btn_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel_Input_GanadorLayout.setVerticalGroup(
            Panel_Input_GanadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Input_GanadorLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(LB_Titulo_Resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(LB_Contenido_Resultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(85, 85, 85))
            .addGroup(Panel_Input_GanadorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LB_Etiqueta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CB_Tipo_Sorteo_Ganador, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LB_Etiqueta2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Campo_Numero_Ganador, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LB_Etiqueta1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Campo_Serie_Ganador, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LB_Etiqueta3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Campo_Numero_Sorteo_Ganador, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(btn_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout Panel_GanadorLayout = new javax.swing.GroupLayout(Panel_Ganador);
        Panel_Ganador.setLayout(Panel_GanadorLayout);
        Panel_GanadorLayout.setHorizontalGroup(
            Panel_GanadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_GanadorLayout.createSequentialGroup()
                .addGroup(Panel_GanadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_GanadorLayout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(LabelTitulo2))
                    .addGroup(Panel_GanadorLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(Panel_Input_Ganador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        Panel_GanadorLayout.setVerticalGroup(
            Panel_GanadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_GanadorLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(LabelTitulo2)
                .addGap(18, 18, 18)
                .addComponent(Panel_Input_Ganador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        Body_Ganador.add(Panel_Ganador, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 78, 960, 470));

        Lb_FondoG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/lottery.png"))); // NOI18N
        Body_Ganador.add(Lb_FondoG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 640));

        getContentPane().add(Body_Ganador, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 62, -1, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SalirActionPerformed
        // TODO add your handling code here:
        Login Ventana = new Login();
        Ventana.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_Btn_SalirActionPerformed

    private void Btn_VerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_VerificarActionPerformed
        // TODO add your handling code here:             
        Body_Estadísticas.setVisible(false);        
        Body_Inicio.setVisible(false);
        Body_Ganador.setVisible(true);
    }//GEN-LAST:event_Btn_VerificarActionPerformed

    private void Btn_EstadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_EstadisticasActionPerformed
        // TODO add your handling code here:        
        Body_Inicio.setVisible(false);
        Body_Ganador.setVisible(false);
        Body_Estadísticas.setVisible(true);
    }//GEN-LAST:event_Btn_EstadisticasActionPerformed

    private void Btn_InicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_InicioActionPerformed
        // TODO add your handling code here:
        Body_Ganador.setVisible(false);
        Body_Estadísticas.setVisible(false);        
        Body_Inicio.setVisible(true);        
    }//GEN-LAST:event_Btn_InicioActionPerformed

    private void btn_buscar_exportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscar_exportarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_buscar_exportarActionPerformed

    private void btn_buscar_estadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscar_estadisticasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_buscar_estadisticasActionPerformed

    private void btn_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_BuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Body_Estadísticas;
    private javax.swing.JPanel Body_Ganador;
    private javax.swing.JPanel Body_Inicio;
    private javax.swing.JButton Btn_Estadisticas;
    private javax.swing.JButton Btn_Inicio;
    private javax.swing.JButton Btn_Salir;
    private javax.swing.JButton Btn_Verificar;
    private javax.swing.JComboBox<String> CB_Consulta_estadistica;
    private javax.swing.JComboBox<String> CB_Filtro_estadistica;
    private javax.swing.JComboBox<String> CB_Tipo_Exportar;
    private javax.swing.JComboBox<String> CB_Tipo_Sorteo_Ganador;
    private javax.swing.JTextField Campo_Numero_Exportar;
    private javax.swing.JTextField Campo_Numero_Ganador;
    private javax.swing.JTextField Campo_Numero_Sorteo_Ganador;
    private javax.swing.JTextField Campo_Serie_Ganador;
    private javax.swing.JPanel Header;
    private javax.swing.JLabel LB_Contenido_Resultado;
    private javax.swing.JLabel LB_Etiqueta;
    private javax.swing.JLabel LB_Etiqueta1;
    private javax.swing.JLabel LB_Etiqueta2;
    private javax.swing.JLabel LB_Etiqueta3;
    private javax.swing.JLabel LB_PP_Monto_Chances;
    private javax.swing.JLabel LB_PP_Monto_Loteria;
    private javax.swing.JLabel LB_PP_Numero_Chances;
    private javax.swing.JLabel LB_PP_Numero_Loteria;
    private javax.swing.JLabel LB_PP_Serie_Chances;
    private javax.swing.JLabel LB_PP_Serie_Loteria;
    private javax.swing.JLabel LB_SP_Monto_Chances;
    private javax.swing.JLabel LB_SP_Monto_Loteria;
    private javax.swing.JLabel LB_SP_Numero_Chances;
    private javax.swing.JLabel LB_SP_Numero_Loteria;
    private javax.swing.JLabel LB_SP_Serie_Chances;
    private javax.swing.JLabel LB_SP_Serie_Loteria;
    private javax.swing.JLabel LB_TP_Monto_Chances;
    private javax.swing.JLabel LB_TP_Monto_Loteria;
    private javax.swing.JLabel LB_TP_Numero_Chances;
    private javax.swing.JLabel LB_TP_Numero_Loteria;
    private javax.swing.JLabel LB_TP_Serie_Chances;
    private javax.swing.JLabel LB_TP_Serie_Loteria;
    private javax.swing.JLabel LB_Titulo;
    private javax.swing.JLabel LB_Titulo_Chances;
    private javax.swing.JLabel LB_Titulo_Loteria;
    private javax.swing.JLabel LB_Titulo_Resultado;
    private javax.swing.JLabel LabelTitulo;
    private javax.swing.JLabel LabelTitulo1;
    private javax.swing.JLabel LabelTitulo2;
    private javax.swing.JLabel Label_Fecha_Chances;
    private javax.swing.JLabel Label_Fecha_Loteria;
    private javax.swing.JLabel Lb_FondoG;
    private javax.swing.JLabel Lb_FondoG1;
    private javax.swing.JLabel Lb_FondoI;
    private javax.swing.JTabbedPane Panel_Contenedor_Estadisticas;
    private javax.swing.JPanel Panel_EXportar;
    private javax.swing.JPanel Panel_Estadisticas;
    private javax.swing.JPanel Panel_Ganador;
    private javax.swing.JPanel Panel_Inicio_Chances;
    private javax.swing.JPanel Panel_Inicio_Loteria;
    private javax.swing.JPanel Panel_Input_Ganador;
    private javax.swing.JTable Tabla_Estadisticas;
    private javax.swing.JTable Tabla_Exportar;
    private javax.swing.JButton btn_Buscar;
    private javax.swing.JButton btn_buscar_estadisticas;
    private javax.swing.JButton btn_buscar_exportar;
    private javax.swing.JButton btn_exportar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    // End of variables declaration//GEN-END:variables
}
